<?php $this->layout('layout::default', ['title' => 'Home']) ?>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="/">
            <img src="/imgs/marca.png" class="d-inline-block align-top" height="35" alt="">
        </a>
        <div class="my-2 my-lg-0">
            <a id="github-link" href="https://github.com/andersonluciano/rest-hero"><i class="fa fa-github"></i></a>
        </div>
    </nav>

    <div class="row " id="env-general">
        <div class="col-3" style="transition-duration: 1s;">
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <input type="text" id="search-input" class="form-control" placeholder="Search and Enter">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <ul class="list-group" id="last-requests">

                    </ul>
                </div>
            </div>

        </div>
        <div class="col-9" id="env-app">
            <div class="row">
                <div class="col-2">
                    <div class="form-group">
                        <select class="form-control" id="method">
                            <option value="GET">GET</option>
                            <option value="POST">POST</option>
                            <option value="PUT">PUT</option>
                            <option value="DELETE">DELETE</option>
                        </select>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="URL and Enter" id="url">
                    </div>
                </div>
                <div class="col-2">
                    <button id="btn-send" type="button" class="btn btn-outline-secondary float-right"><i class="fa fa-paper-plane"></i> Enviar</button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="btn-group" role="group" aria-label="Options">
                        <button id="btn-toogle-header" type="button" class="btn btn-sm btn-dark" data-toggle="tooltip" data-placement="top" title="Headers"><i class="fa fa-bars"></i></button>
                        <button id="btn-toogle-basic-auth" type="button" class="btn btn-sm btn-dark" data-toggle="tooltip" data-placement="top" title="Basic Auth"><i class="fa fa-key"></i></button>
                    </div>
                </div>
            </div>

            <div class="row" id="env-headers" style="display: none;">

                <div class="col">
                    <hr>
                    <label for="exampleInputEmail1">Headers</label>
                    <textarea class="form-control" id="headers" rows="3" placeholder="Headers"></textarea>
                </div>
            </div>

            <div class="row" id="env-basic-auth" style="display: none;">
                <div class="col">
                    <hr>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Basic Auth</label>
                        <input type="text" class="form-control" id="basicauth-user" placeholder="User">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="basicauth-secret" placeholder="Secret">
                        <small id="emailHelp" class="form-text text-muted">After typed will be converted in a header</small>
                    </div>
                    <button type="button" id="btn-generate-basic" class="btn btn-secondary mb-2 float-right"><i class="fa fa-refresh"></i> Update</button>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col">
                    <p>Body</p>
                    <div id="editor"></div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col">
                    <p>Response</p>
                    <p id="status-code"></p>
                    <div id="response"></div>
                </div>
            </div>
        </div>
    </div>


<?php
$this->start("javascript");
?>
    <script src="/assets/3-party/toastr/build/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.3.3/ace.js"></script>
    <script>

        var responseEditor = ace.edit("response");
        responseEditor.setTheme("ace/theme/monokai");
        responseEditor.session.setMode("ace/mode/json");

        editor = ace.edit("editor");
        editor.setTheme("ace/theme/monokai");
        editor.session.setMode("ace/mode/json");


        $(function () {
            url = localStorage.getItem("url");
            method = localStorage.getItem("method");
            headers = localStorage.getItem("headers");
            body = localStorage.getItem("body");

            editor.commands.addCommand({
                name: "send",
                exec: function () {
                    send();
                },
                bindKey: {win: 'Ctrl+Enter'}
            });


            $("#url").val(url);
            $("#method").val(method);
            $("#headers").val(headers);
            if (body != null) {
                editor.setValue(body);
            }


//----------------------------
            $("#method").change(function () {
                if ($(this).val() == "POST" || $(this).val() == "PUT") {
                    $("#editor").slideDown(500);
                } else {
                    $("#editor").slideUp(500);
                }
            });
            setTimeout(function () {
                $("#method").change();
            }, 1000);

//----------------------------
            $("#btn-send").click(send);
            $("#url").keydown(function (e) {
                if (e.keyCode == 13) {
                    send();
                }
            });
//----------------------------
            $("#btn-generate-basic").click(function () {
                var auth = '\nAuthorization: Basic ' + btoa($("#basicauth-user").val() + ':' + $("#basicauth-secret").val());
                var headers = $("#headers").val();
                $("#headers").val(headers + auth);
            });
//----------------------------
            $("#search-input").change(function () {
                if ($(this).val() == "") {
                    loadLastRequests();
                }
            });
            $("#search-input").keydown(function (e) {
                if (e.keyCode == 13) {
                    if ($(this).val() == "") {
                        loadLastRequests();
                    } else {
                        $.ajax("/?ajax=searchRequest", {
                            method: "POST",
                            data: {
                                request: $("#search-input").val()
                            }
                        }).done(function (response) {
                            if (response.exception == undefined) {
                                $("#last-requests").html("");
                                $(response).each(function (idx, elem) {
                                    makeListItem(elem);
                                });
                            } else {
                                toastr.error("Nenhum registro encontrado: " + response.exception);
                            }
                        });
                    }
                }
            });

            $('[data-toggle="tooltip"]').tooltip();

            $("#btn-toogle-basic-auth").click(function () {
                $("#env-basic-auth").toggle("fast");
            });
            $("#btn-toogle-header").click(function () {
                $("#env-headers").toggle("fast");
            });


            loadLastRequests();
        });

        function send() {

            $("#btn-send").html("<i class='fa fa-spin fa-refresh'></i> Enviando...");
            $("#btn-send").attr("disabled", true);


            var url = $("#url").val();
            var method = $("#method").val();
            var headers = $("#headers").val();
            var body = "";
            if (method == "POST" || method == "PUT") {
                var body = editor.getValue();
            }


            localStorage.setItem("url", url);
            localStorage.setItem("method", method);
            localStorage.setItem("headers", headers);
            localStorage.setItem("body", body);

            $("#status-code").html("Enviando...");
            responseEditor.setValue("");

            var data = {
                url: url,
                method: method,
                headers: headers,
                body: body
            };
            $.ajax("/send", {
                method: "POST",
                data: data
            }).done(function (response) {
                if (response.body != "") {

                    try {
                        var json = JSON.parse(response.body);
                    } catch (e) {
                        var json = null;
                    }
                    if (json != null && json != undefined) {
                        response.body = JSON.stringify(json, null, "\t"); // Indented with tab
                    }
                }

                $("#status-code").html(response.statusCode + " - " + response.time + "s");
                responseEditor.setValue(response.body);


                $("#btn-send").html("<i class='fa fa-paper-plane'></i> Enviar");
                $("#btn-send").removeAttr("disabled");

                if (response.refreshList == true) {
                    data.created_at = "Agora"
                    makeListItem(data, true);
                }
            }).error(function (response) {

                toastr.error("Ocorreu algum problema durante a requisição");

                $("#status-code").html(response.status);
                if (response.responseText != undefined) {
                    responseEditor.setValue(response.responseText);
                }

                $("#btn-send").html("<i class='fa fa-paper-plane'></i> Enviar");
                $("#btn-send").removeAttr("disabled");
            });
        }

        function loadLastRequests() {
            $.ajax("/?ajax=loadRequests", {
                method: "POST"
            }).done(function (response) {
                if (response.exception == undefined) {
                    $("#last-requests").html("");
                    $(response).each(function (idx, elem) {
                        makeListItem(elem);
                    });
                }
            });
        }

        function makeListItem(elem, prepend) {
            var li = $("<li class='list-group-item' style='display: none;'>");
            var badgeClass = "";
            switch (elem.method) {
                case "GET":
                    badgeClass = 'badge-primary';
                    break;
                case "POST":
                    badgeClass = 'badge-success';
                    break;
                case "PUT":
                    badgeClass = 'badge-warning';
                    break;
                case "DELETE":
                    badgeClass = 'badge-danger';
                    break;
            }

            $(li).html('<span class="badge ' + badgeClass + '">' + elem.method + "</span><br>" + elem.url + "<br><small>" + elem.created_at + "</small>");
            if (prepend != undefined) {
                $("#last-requests").prepend(li);
            } else {
                $("#last-requests").append(li);
            }

            $(li).click(function () {
                $("#url").val(elem.url);
                $("#method").val(elem.method);
                $("#headers").val(elem.headers);
                editor.setValue(elem.body);
                $("#method").change();
            });
            $(li).fadeIn(500);
        }
    </script>
<?php
$this->stop("javascript");
?>

<?php
$this->start("stylesheets");
?>
    <link rel="stylesheet" href="/assets/3-party/toastr/build/toastr.min.css">
    <style>
        #github-link {
            font-size: 43px;
            color: #333;
        }

        #github-link:hover {
            color: #E03A3E;
        }

        #env-general {
            margin-top: 30px;
            margin-bottom: 30px;
        }

        #editor {
            height: 250px;
        }

        #response {
            height: 500px;
        }

        .list-group-item {
            font-size: 13px;
            word-wrap: break-word;
            cursor: pointer;

        }

        .list-group-item:hover {
            background: #e2e2e2;
        }

        #last-requests {
            height: 500px;
            overflow-y: scroll;
        }

        #env-app {
            border-left: 1px solid #e2e2e2;
            border-bottom: 1px solid #e2e2e2;
            padding-bottom: 15px;
        }


    </style>

<?php
$this->stop("stylesheets");
?>